### ISSUE TITLE
Kodi crashes when trying to run the add-on

### ISSUE THREAD

**Issue by j00ch** [kodi-game/game.libretro.vice#3] opened 2019-12-27 23:28 UTC
Kodi crashes when i try to run the the add-on.

Here is a clear and concise description of what happens in RetroArch with the same core/game:
No problems when i run the add-on under RetroArch, games also work.

1. Build this add-on on Arch Linux
2. Run Kodi
3. Run the add-on

The debuglog can be found here:
[kodi_crashlog-20191227_232353.log](https://github.com/kodi-game/game.libretro.vice/files/4006452/kodi_crashlog-20191227_232353.log)

Used Operating system:
Arch Linux (Kernel: x86_64 5.4.6-2)

Kodi version:
18.5 Git:20191116

**Comment by garbear** [comment] 2019-12-29 03:00
Looks like another crash due to not handling the libretro API properly (Kodi requires stricter conformance than RetroArch). I'll look into this when I get a chance

**Comment by garbear** [comment] 2020-01-10 14:47
Sorry, never got a chance. Don't have time to fix this one yet.

**Comment by thirtywinter** [comment] 2020-04-18 16:57
Just wanted to throw in that I am having the exact same problem on the windows platform. Hardcrash out to windows as soon as I try to start it (It did seem to start up the first time I tried it mind you. At least I got that picture of the controller up on screen before I had to go to some other stuff.  Never could get it to run again.

Also, my log file looks damn pretty much similar to the one already posted.

**Comment by garbear** [comment] 2020-04-18 17:24
Thanks for the confirmation. I probably won't have time to bug-hunt through add-ons in the near future, but feel free to ping over the summer when I've allocated some time for GSoC.

**Comment by marplar** [comment] 2020-07-25 14:35
Just wanted to add that I seem to have the same issue on Android. The errors in the log look the same as the one already posted.

**Comment by inf0rmix** [comment] 2021-10-15 11:57
Is there any hint how to fix this ? Just to have a starting point ...

I see many setting errors on startup on ubuntu focal:


.....
[ERROR] Unknown setting ID: vice_read_vicerc
[ERROR] Unknown setting ID: vice_mapper_select
[ERROR] Unknown setting ID: vice_mapper_start
....

**Comment by garbear** [comment] 2021-10-15 12:04
I updated all 130 of our libretro cores, and most should be on the mirrors by now. Can you try Vice version 3.5.0.17?

**Comment by inf0rmix** [comment] 2022-02-10 10:49
I cannot build the vice package from focal sources of 3.5.0.20:

-- Install configuration: "Release"
CMake Error at cmake_install.cmake:49 (file):
  file INSTALL cannot find
  "/home/XXXXX/git/kodi-game-libretro-vice-3.5.0.20/VICE_LIB-NOTFOUND": No
  such file or directory.

how do I install this dependency ?

**Comment by inf0rmix** [comment] 2022-02-10 10:55
solved it by myself - vice_x64_libretro.so was missing. testing in kodi soon.

**Comment by garbear** [comment] 2022-02-10 21:16
I'm not seeing a crash (but on my dev branch keyboard is disabled and I can't get past the BIOS)

![Screenshot from 2022-02-10 12-56-50](https://user-images.githubusercontent.com/531482/153496977-d877b5fb-5def-4749-9409-4b16add5ad95.png)

In my debug log:

```
2022-02-10 13:13:36.670 T:23410    INFO <general>: AddOnLog: game.libretro.vice: Tape: T64 image '/home/xxx/.kodi/userdata/addon_data/plugin.program.iagl/game_cache/Archon II - Adept (USA).t64' attached.
```

A full debug log would have additional info and I could look for differences with my machine that might cause the crash. If I can reproduce, then I can debug Vice and figure out why it's crashing with your ROMs.

**Comment by inf0rmix** [comment] 2022-02-14 09:05
wonderful - what do you need exactly? And how to enable full debug ?

**Comment by garbear** [comment] 2022-02-14 22:31
> wonderful - what do you need exactly? And how to enable full debug ?

Search "kodi debug log". There are two links:

* The easy way: https://kodi.wiki/view/Log_file/Easy
* The normal way: https://kodi.wiki/view/Log_file

One of those two should work for you.

Full logs work best. A paste site like http://paste.kodi.tv/ or https://paste.ubuntu.com/ works better than pasting the entire log into github comments.

**Comment by inf0rmix** [comment] 2023-01-26 08:03
Im now with kodi 20 on ubuntu 2204/jammy and vice is working. I only have a problem configuring the controller. I also have issues with the config menu and missing warp mode. The hotkeys do not seem to work.

my vice/kodi-addon version is:
kodi-game-libretro-vice                       6:3.5.0.23-1~jammy

**Comment by garbear** [comment] 2023-01-26 19:49
You can see that the latest version is 3.5.0.33 here: https://github.com/kodi-game/game.libretro.vice/tags

Previously there was a lot of issues with settings which I fixed about 4 days ago: https://github.com/kodi-game/vice-libretro/commit/3934cf8b507a14376d99971ef364fc6c7386ba5e

There may be an advanced option that allows fine-tuning how the controls work. PCSX-Rearmed, for example, requires you to set analog mode for controllers in the advanced settings before some games will work. Without a debug log, the best I can suggest is that you update to version 3.5.0.33, which may require building from source.

However, if you provide a debug log, then I'll have all the information I need to reproduce the problem.

Anyways, thanks for trying again after all this time!

**Comment by garbear** [comment] 2023-03-18 20:18
Closing the GH issue, as the original crash is solved. @inf0rmix you can open another GH issue to move your problem forward.

**Closed by garbear** 2023-03-18 20:18 UTC
